services:
  app:
    image: "joelgalvez/publicdata:latest"
    build: .
    ports:
      - 3001:3000
  
  cron:
    image: "joelgalvez/publicdata:latest"
    build: .
    command: "cron -f"
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      disable: true
